language: node_js
node_js:
  - 18

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t hoangthiendocker1996/udagram-frontend .
  - docker tag udagram-frontend hoangthiendocker1996/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hoangthiendocker1996/udagram-frontend